apiVersion: v1
kind: Service
metadata:
  name: transaction-history-service
  namespace: transaction-history
spec:
  selector:
    app: transaction-history-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
