apiVersion: v1
kind: Service
metadata:
  name: account-management-service
  namespace: account-management
spec:
  selector:
    app: account-management-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
