apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: transaction-history
  namespace: transaction-history
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-history
  template:
    metadata:
      labels:
        app: transaction-history
    spec:
      containers:
      - name: transaction-history
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: transaction-history-active
      previewService: transaction-history-preview
      autoPromotionEnabled: false
