apiVersion: v1
kind: Service
metadata:
  name: transaction-history-active
  namespace: transaction-history
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: transaction-history
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-history-preview
  namespace: transaction-history
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: transaction-history
  type: ClusterIP
