apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: account-service
  namespace: account-management
spec:
  replicas: 4
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: nginxdemos/hello
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {duration: 10s}
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 75
      - pause: {duration: 10s}
